source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorPicker_Example' do
  pod "ColorPicker" , :path => "../"
end

target 'ColorPicker_Tests' do
  pod "ColorPicker" , :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
